### ISSUE TITLE
Double spell cooldown timers

### ISSUE THREAD

**Issue by Addonman** [SLOKnightfall/Ion#31]
If you use Omnicc and Ion toghether you get double coooldowntimers-Reason for it might be that cooldown timers options in ion dont work,i tried removing it in options and it didnt do anything to timers

**Comment by SLOKnightfall** [comment]
Ill look into it, but I believe that the double timers is an issue caused by OmniCC as its been reported on its [bug site ](https://github.com/tullamods/OmniCC/issues/137 )and a lot of times on the [Curse page](https://mods.curse.com/addons/wow/omni-cc)

**Comment by Addonman** [comment]
Back in the day there was something conflicting between Ion and Omnicc  and even reported back then  ([https://github.com/tullamods/OmniCC/issues/62] not sure if it was fixed back then a right way.Didnt really play WOW much since then but seems similar issue. Not sure if you can turn original Ion timers somehow off and leave only Omnicc but timer options seemed broken for me and if fixed possiable solution.

**Comment by SLOKnightfall** [comment]
I did some testing and it looks like the issue is with OmniCC not ION.  Ion timers are off by default, so the double numbers are from not from ION.  You can see this easily by changing the colors of the ION cooldown counter via the bar settings, and neither of the sets of numbers getting displayed will have the colors.
The ticket you linked actually shows that OmniCC is hooking the ION cooldown frame to display its counters and there is nothing that ION can do to change what gets displayed.

**Comment by Addonman** [comment]
I did some more checking and it seems that double cooldown spells are present for spell like roll on momk or paladin crusader strike where there are charges.I test Omnicc on blizz bars then everthing is normal so i am not 100% sure thats its Omnicc fault for showing those double numbers. Can it be that because the way ION (like macros? ) is seting up spells and Ion cant tell Omnicc that is spell with charges Omnicc gives double cooldowns-BTW double cooldowns are happening on second (last ) charge,after using 1st charge numbers are ok,but on 2nd they double.

**Comment by SLOKnightfall** [comment]
Omnicc is what creates the cooldowns so there is nothing on ION's end to fix.  If you want the issue fixed, then it its in the hands of the Omnicc author.

**Comment by Addonman** [comment]
If that is correct, please explain to me then -Blizzard bars + Omnicc= no double cooldowns numbers, ION +Omnicc =double cooldown numbers? If ION is not a problem here shouldn't Omnicc have same problems with Blizzard bar as well? I am not great at cutting, but doesn't that sound a little bit illogical?
Also, if I remember correctly reading that ION to be able to have all that flexibility is creating a button as some sort of macros-could it be that Omnicc sees those 2 button presses as two different macros so is then created 2 sets of numbers on the same spot?

And on topic of Omnicc author willingness to fix problems with ION-i remember  reported bug  where he did something a certain way(caused for ION users to have no numbers at all) and fixing it to work specifically for  ION would cause to brake certain functions of Omnicc and ofc he wasnt willing to do so i dont hope for that in this case as well

**Comment by SLOKnightfall** [comment]
Because the Blizzard bars are different than ION bars.  The numbers you see are from Omnicc, where it gets its data from I don't know.  There may be some interaction with ION that is causing the double cool downs, but once again the issue is how Omnicc is displaying its cooldowns and there is nothing I can do to fix it.
